INSERT INTO Genre (nom) VALUES ('Horror');
INSERT INTO Genre (nom) VALUES ('Comedy');
INSERT INTO Genre (nom) VALUES ('Action');
INSERT INTO Genre (nom) VALUES ('Romance');
INSERT INTO Genre (nom) VALUES ('Adventure');
INSERT INTO Genre (nom) VALUES ('Historical');
INSERT INTO Genre (nom) VALUES ('Sci-Fi');
INSERT INTO Genre (nom) VALUES ('Fantastic');
INSERT INTO Genre (nom) VALUES ('Crime');
INSERT INTO Genre (nom) VALUES ('Documentary');
INSERT INTO Genre (nom) VALUES ('Thriller');
INSERT INTO Genre (nom) VALUES ('Tragedy');
INSERT INTO Genre (nom) VALUES ('Drama');
INSERT INTO Genre (nom) VALUES ('Game show');
INSERT INTO Genre (nom) VALUES ('Mystery');
INSERT INTO Genre (nom) VALUES ('Reality TV');
INSERT INTO Genre (nom) VALUES ('Western');
INSERT INTO Genre (nom) VALUES ('Noir');

INSERT INTO Type (nom) VALUES ('RPG');
INSERT INTO Type (nom) VALUES ('Online');
INSERT INTO Type (nom) VALUES ('VR');
INSERT INTO Type (nom) VALUES ('Multiplayer');
INSERT INTO Type (nom) VALUES ('Simulation');
INSERT INTO Type (nom) VALUES ('Reflexion');
INSERT INTO Type (nom) VALUES ('Souls like');
INSERT INTO Type (nom) VALUES ('Rogue like');
INSERT INTO Type (nom) VALUES ('Metroidvania');
INSERT INTO Type (nom) VALUES ('Gestion');
INSERT INTO Type (nom) VALUES ('Arcade');
INSERT INTO Type (nom) VALUES ('Rythm');
INSERT INTO Type (nom) VALUES ('Combat');
INSERT INTO Type (nom) VALUES ('Hack and Slash');
INSERT INTO Type (nom) VALUES ('Plateformer');
INSERT INTO Type (nom) VALUES ('Shoot them up');
INSERT INTO Type (nom) VALUES ('FPS');
INSERT INTO Type (nom) VALUES ('TPS');
INSERT INTO Type (nom) VALUES ('Sandbox');
INSERT INTO Type (nom) VALUES ('Racing');
INSERT INTO Type (nom) VALUES ('Strategy');
INSERT INTO Type (nom) VALUES ('Tower defense');
INSERT INTO Type (nom) VALUES ('Cards and Board');
INSERT INTO Type (nom) VALUES ('Light Novel');

