INSERT INTO Genre("Horror");
INSERT INTO Genre("Comedy");
INSERT INTO Genre("Action");
INSERT INTO Genre("Romance");
INSERT INTO Genre("Adventure");
INSERT INTO Genre("Historical");
INSERT INTO Genre("Sci-Fi");
INSERT INTO Genre("Fantastic");
INSERT INTO Genre("Crime");
INSERT INTO Genre("Documentary");
INSERT INTO Genre("Thriller");
INSERT INTO Genre("Tragedy");
INSERT INTO Genre("Drama");
INSERT INTO Genre("Game show");
INSERT INTO Genre("Mistery");
INSERT INTO Genre("Reality TV");
INSERT INTO Genre("Western");
INSERT INTO Genre("Noir");

INSERT INTO Type("RPG");
INSERT INTO Type("Online");
INSERT INTO Type("VR");
INSERT INTO Type("Multiplayer");
INSERT INTO Type("Simulation");
INSERT INTO Type("Reflexion");
INSERT INTO Type("Souls like");
INSERT INTO Type("Rogue like");
INSERT INTO Type("Metroidvania");
INSERT INTO Type("Gestion");
INSERT INTO Type("Arcade");
INSERT INTO Type("Rythm");
INSERT INTO Type("Combat");
INSERT INTO Type("Hack and Slash");
INSERT INTO Type("Plateformer");
INSERT INTO Type("Shoot the up");
INSERT INTO Type("FPS");
INSERT INTO Type("TPS");
INSERT INTO Type("Sandbox");
INSERT INTO Type("Racing");
INSERT INTO Type("Strategy");
INSERT INTO Type("Tower defense");
INSERT INTO Type("Cards and Board");
INSERT INTO Type("Light Novel");

